<#
.SYNOPSIS
    Collects endpoint/device information and writes a Markdown report.
.DESCRIPTION
    Device audit helper for Windows. Produces the same report layout as
    device-audit.sh so that Linux, macOS and Windows output can be compared.
.EXAMPLE
    .\DeviceAudit.ps1
.EXAMPLE
    .\DeviceAudit.ps1 -OutputFile .\audit.md -IncludeSoftware
#>
[CmdletBinding()]
param(
    [string] $OutputFile,
    [switch] $IncludeSoftware,
    [switch] $Quiet
)

$ErrorActionPreference = 'SilentlyContinue'
$ProgressPreference = 'SilentlyContinue'

$Version = '1.0.0'
$ScriptName = 'DeviceAudit.ps1'

if (-not $OutputFile) {
    $OutputFile = Join-Path (Get-Location) ("device-audit-{0}-{1}.md" -f $env:COMPUTERNAME, (Get-Date -Format 'yyyyMMdd-HHmmss'))
}

$sb = New-Object System.Text.StringBuilder

# Escape pipes and collapse newlines so values cannot break the Markdown table.
function Clean([object] $Value) {
    if ($null -eq $Value) { return '' }
    $s = [string]$Value
    $s = $s -replace '[\r\n\t]', ' '
    $s = $s -replace '\|', '\|'
    $s = $s -replace '\s{2,}', ' '
    return $s.Trim()
}

function Val([object] $Value) {
    $s = Clean $Value
    if ([string]::IsNullOrWhiteSpace($s) -or $s -eq 'unknown' -or $s -eq 'not available') { return '_n/a_' }
    return $s
}

function Add-Line([string] $Text = '') { [void]$sb.AppendLine($Text) }
function Add-Section([string] $Title) { Add-Line ''; Add-Line "## $Title"; Add-Line '' }
function Add-KV([string] $Key, [object] $Value) { Add-Line ('| {0} | {1} |' -f (Clean $Key), (Val $Value)) }
function Add-Row([object] $Value) { Add-Line ('| {0} |' -f (Val $Value)) }
function Add-TableHead([string] $Columns) {
    Add-Line ('| {0} |' -f $Columns)
    $seps = (($Columns -split '\|') | ForEach-Object { '---' }) -join '|'
    Add-Line ('| {0} |' -f $seps)
}

# Run a command and return its output, or $null if it fails.
function Try-Run([scriptblock] $Block) {
    try { return (& $Block 2>$null | Out-String).Trim() } catch { return $null }
}

# Same, but returns the objects themselves (needed for CIM property access).
function Try-Get([scriptblock] $Block) {
    try { return (& $Block 2>$null) } catch { return $null }
}

function Is-Admin {
    try {
        $id = [Security.Principal.WindowsIdentity]::GetCurrent()
        return (New-Object Security.Principal.WindowsPrincipal($id)).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    } catch { return $false }
}

# ----------------------------------------------------------------- report start
$os   = Try-Get { Get-CimInstance Win32_OperatingSystem }
$cs   = Try-Get { Get-CimInstance Win32_ComputerSystem }
$cpu  = Try-Get { Get-CimInstance Win32_Processor | Select-Object -First 1 }
$bios = Try-Get { Get-CimInstance Win32_BIOS }

Add-Line '# Device Audit Report'
Add-Line ''
Add-Line ('- **Host name:** {0}' -f (Clean $env:COMPUTERNAME))
Add-Line ('- **Report generated:** {0}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))
Add-Line ('- **Generated by:** {0} {1}' -f $ScriptName, $Version)
if (Is-Admin) {
    Add-Line '- **Privilege level:** administrator (elevated - full hardware inventory available)'
} else {
    Add-Line '- **Privilege level:** standard user (re-run as administrator for serial number and some BIOS values)'
}
Add-Line ''

# -------------------------------------------------------------------- overview
Add-Section 'Overview'
Add-Line '| Field | Value |'
Add-Line '| --- | --- |'
Add-KV 'Operating system' $os.Caption
Add-KV 'OS version' $os.Version
Add-KV 'OS build' $os.BuildNumber
Add-KV 'Service pack' $os.ServicePackMajorVersion
Add-KV 'Architecture' $os.OSArchitecture
Add-KV 'Host name' $env:COMPUTERNAME
Add-KV 'Current user' ("{0}\{1}" -f $env:USERDOMAIN, $env:USERNAME)
Add-KV 'Last boot' $os.LastBootUpTime
Add-KV 'Uptime' (Try-Run { '{0:0} since {1}' -f ((Get-Date) - $os.LastBootUpTime), $os.LastBootUpTime })
Add-KV 'Timezone' (Try-Run { (Get-TimeZone).Id })
Add-KV 'Locale' (Try-Run { (Get-Culture).Name })
Add-KV 'Installed on' $os.InstallDate

# -------------------------------------------------------------------- hardware
Add-Section 'Hardware'
Add-Line '| Field | Value |'
Add-Line '| --- | --- |'
Add-KV 'Manufacturer' $cs.Manufacturer
Add-KV 'Model' $cs.Model
Add-KV 'System type' $cs.SystemType
Add-KV 'Chassis' (Try-Run { (Get-CimInstance Win32_SystemEnclosure | Select-Object -First 1).ChassisTypes })
Add-KV 'CPU' $cpu.Name
Add-KV 'Cores (physical)' $cpu.NumberOfCores
Add-KV 'Cores (logical)' $cpu.NumberOfLogicalProcessors
Add-KV 'CPU max speed (MHz)' $cpu.MaxClockSpeed
Add-KV 'Memory' (Try-Run { '{0:N2} GiB' -f ($cs.TotalPhysicalMemory / 1GB) })
Add-KV 'Serial number' $bios.SerialNumber
Add-KV 'UUID' $cs.UUID
Add-KV 'BIOS vendor' $bios.Manufacturer
Add-KV 'BIOS version' $bios.SMBIOSBIOSVersion
Add-KV 'Asset tag' $cs.Tag
Add-KV 'Secure boot' (Try-Run { if (Confirm-SecureBootUEFI) { 'enabled' } else { 'disabled' } })
Add-KV 'Virtualization present' (Try-Run { $cs.HypervisorPresent })
Add-KV 'Part of domain' (Try-Run { $cs.PartOfDomain })
Add-KV 'Domain' (Try-Run { $cs.Domain })

# -------------------------------------------------------------------- storage
Add-Section 'Storage'
Add-Line '| Disk | Index | Model | Size (GB) | Type | Interface | Status |'
Add-Line '| --- | --- | --- | --- | --- | --- | --- |'
$disks = Try-Get { Get-CimInstance Win32_DiskDrive }
foreach ($d in $disks) {
    $sizeGb = [math]::Round($d.Size / 1GB, 1)
    Add-Line ('| {0} | {1} | {2} | {3} | {4} | {5} | {6} |' -f `
        (Val $d.DeviceID), $d.PartitionIndex, (Val $d.Model), $sizeGb, (Val $d.MediaType), (Val $d.InterfaceType), (Val $d.Status))
}
Add-Line ''
Add-Line '| Volume | Drive | File system | Size (GB) | Free (GB) | Label |'
Add-Line '| --- | --- | --- | --- | --- | --- |'
$vols = Try-Get { Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3' }
foreach ($v in $vols) {
    Add-Line ('| {0} | {1} | {2} | {3} | {4} | {5} |' -f `
        (Val $v.VolumeName), (Val $v.DeviceID), (Val $v.FileSystem),
        [math]::Round($v.Size / 1GB, 1), [math]::Round($v.FreeSpace / 1GB, 1), (Val $v.VolumeName))
}

# -------------------------------------------------------------------- network
Add-Section 'Network'
Add-Line '| Adapter | Description | MAC address | IPv4 | IPv6 | Status |'
Add-Line '| --- | --- | --- | --- | --- | --- |'
$nics = Try-Get { Get-CimInstance Win32_NetworkAdapter -Filter 'PhysicalAdapter=True' }
foreach ($n in $nics) {
    $cfg = Try-Get { Get-CimInstance Win32_NetworkAdapterConfiguration -Filter ("InterfaceIndex={0}" -f $n.InterfaceIndex) } | Select-Object -First 1
    $ipv4 = (($cfg | Select-Object -ExpandProperty IPAddress) -join ', ')
    $ipv6 = (($cfg | Select-Object -ExpandProperty IPv6Address) -join ', ')
    $gw = (($cfg | Select-Object -ExpandProperty DefaultIPGateway) -join ', ')
    Add-Line ('| {0} | {1} | {2} | {3} | {4} | {5} |' -f `
        (Val $n.Name), (Val $n.NetConnectionID), (Val $n.MACAddress), (Val $ipv4), (Val $ipv6), (Val $n.NetEnabled))
}

Add-Line ''
Add-Section 'Network configuration'
Add-Line '| Field | Value |'
Add-Line '| --- | --- |'
$ipcfg = Try-Get { Get-NetIPConfiguration | Where-Object { $_.IPv4Address } | Select-Object -First 1 }
Add-KV 'FQDN' (Try-Run { [System.Net.Dns]::GetHostEntry($env:COMPUTERNAME).HostName })
Add-KV 'Domain DNS suffix' (Try-Run { (Get-CimInstance Win32_ComputerSystem).Domain })
Add-KV 'Primary IPv4' (Val $ipcfg.IPv4Address.IPAddress)
Add-KV 'Subnet mask' (Val $ipcfg.IPv4Address.PrefixLength)
Add-KV 'Default gateway' (Val ($ipcfg.IPv4DefaultGateway.NextHop))
Add-KV 'DNS servers' (Val (($ipcfg.DNSServer.ServerAddresses) -join ', '))
Add-KV 'DNS suffix' (Val $ipcfg.DNSDomain)
Add-KV 'DHCP enabled' (Val $ipcfg.Dhcp)
Add-KV 'Profile' (Val (Try-Run { (Get-NetConnectionProfile | Select-Object -First 1).Name }))
Add-KV 'Network category' (Val (Try-Run { (Get-NetConnectionProfile | Select-Object -First 1).NetworkCategory }))
Add-KV 'Wi-Fi SSID' (Val (Try-Run { (netsh wlan show interfaces | Select-String '^\s+SSID\s+:' | Select-Object -First 1) -replace '.*:\s+', '' }))
Add-KV 'Proxy' (Val (Try-Get { (Get-ItemProperty 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings').ProxyServer }))

# ------------------------------------------------------------------ displays
Add-Section 'Displays'
Add-Line '| Field | Value |'
Add-Line '| --- | --- |'
$mon = Try-Get { Get-CimInstance Win32_DesktopMonitor | Select-Object -First 1 }
Add-KV 'Monitor' (Val (Try-Get { (Get-CimInstance Win32_DesktopMonitor | Select-Object -First 1).Name }))
Add-KV 'Screen size' (Val ("{0} x {1} (depth {2})" -f $mon.ScreenWidth, $mon.ScreenHeight, $mon.PixelDepth))
Add-KV 'Video controller' (Val (Try-Run { (Get-CimInstance Win32_VideoController | Select-Object -First 1).Name }))
Add-KV 'Video memory' (Val (Try-Run { '{0} MB' -f (Get-CimInstance Win32_VideoController | Select-Object -First 1).AdapterRAM / 1MB }))
Add-KV 'Current resolution' (Val (Try-Run { (Get-CimInstance Win32_VideoController | Select-Object -First 1).CurrentHorizontalResolution.ToString() + 'x' + (Get-CimInstance Win32_VideoController | Select-Object -First 1).CurrentVerticalResolution.ToString() }))
Add-KV 'External displays' (Val (Try-Run { (Get-CimInstance Win32_VideoController | Where-Object { $_.CurrentHorizontalResolution }).Count }))

# ------------------------------------------------------------------- battery
Add-Section 'Battery'
Add-Line '| Field | Value |'
Add-Line '| --- | --- |'
$batt = Try-Get { Get-CimInstance Win32_Battery }
$battStatus = @{ 1 = 'Discharging'; 2 = 'AC (plugged in)'; 3 = 'Fully charged'; 4 = 'Low'; 5 = 'Critical'; 6 = 'Charging'; 7 = 'Charging and high'; 8 = 'Charging and low'; 9 = 'Charging and critical'; 11 = 'Undefined' }
if ($batt) {
    Add-KV 'Battery present' 'yes'
    Add-KV 'Charge level %' $batt.EstimatedChargeRemaining
    Add-KV 'Battery status' (Val $battStatus[[int]$batt.BatteryStatus])
    Add-KV 'Design capacity (mWh)' $batt.DesignCapacity
    Add-KV 'Full charge capacity (mWh)' $batt.FullChargeCapacity
    Add-KV 'Health %' (Try-Run { if ($batt.DesignCapacity -gt 0) { [math]::Round(($batt.FullChargeCapacity / $batt.DesignCapacity) * 100, 1) } })
    Add-KV 'Manufacturer' $batt.Manufacturer
    Add-KV 'Device ID' $batt.DeviceID
} else {
    Add-KV 'Battery present' 'no (desktop or no battery detected)'
}

# ------------------------------------------------------------------ security
Add-Section 'Security'
Add-Line '| Field | Value |'
Add-Line '| --- | --- |'
$fw = Try-Get { Get-NetFirewallProfile }
Add-KV 'Firewall profiles' (Val (($fw | ForEach-Object { "$($_.Name)=$($_.Enabled)" }) -join ', '))
Add-KV 'BitLocker' (Val (Try-Run { (Get-BitLockerVolume | Select-Object -First 1).ProtectionStatus }))
Add-KV 'BitLocker encryption' (Val (Try-Run { (Get-BitLockerVolume | Select-Object -First 1).EncryptionMethod }))
Add-KV 'Windows Defender' (Val (Try-Run { (Get-MpComputerStatus).AntivirusEnabled }))
Add-KV 'Real-time protection' (Val (Try-Run { (Get-MpComputerStatus).RealTimeProtectionEnabled }))
Add-KV 'Antivirus signature age (days)' (Val (Try-Run { (Get-MpComputerStatus).AntivirusSignatureAge }))
Add-KV 'Last quick scan' (Val (Try-Run { (Get-MpComputerStatus).QuickScanEndTime }))
Add-KV 'Local administrators' (Val (Try-Run { (Get-LocalGroupMember -Group 'Administrators' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Name) -join ', ' }))
Add-KV 'Auto logon enabled' (Val (Try-Get { (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon').AutoAdminLogon }))
Add-KV 'Screen saver timeout (s)' (Val (Try-Get { (Get-ItemProperty 'HKCU:\Control Panel\Desktop').ScreenSaveTimeOut }))
Add-KV 'Last logged on user' (Val (Try-Run { (Get-CimInstance Win32_LogonSession -Filter "LogonType=2" | Sort-Object LogonTime -Descending | Select-Object -First 1 | ForEach-Object { $_.Name }) -join ', ' }))

# ------------------------------------------------------------------ software
Add-Section 'Software'
Add-Line '| Field | Value |'
Add-Line '| --- | --- |'
Add-KV 'Installed programs' (Val (Try-Run { (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*' | Where-Object { $_.DisplayName }).Count }))
Add-KV 'Last hotfix' (Val (Try-Run { (Get-HotFix | Sort-Object -Property InstalledOn -Descending | Select-Object -First 1).HotFixID }))
Add-KV 'Pending reboot' (Val (Try-Get { (Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending') -or (Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired') }))
Add-KV 'PowerShell version' $PSVersionTable.PSVersion.ToString()
Add-KV 'Installed on' (Val (Try-Get { (Get-CimInstance Win32_OperatingSystem).InstallDate }))

if ($IncludeSoftware) {
    Add-Line ''
    Add-Line '### Installed applications'
    Add-Line ''
    Add-Line '| Application | Version | Publisher |'
    Add-Line '| --- | --- | --- |'
    $paths = @(
        'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',
        'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*',
        'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*'
    )
    $apps = Try-Get { Get-ItemProperty $paths -ErrorAction SilentlyContinue |
        Where-Object { $_.DisplayName } |
        Select-Object DisplayName, DisplayVersion, Publisher } |
        Sort-Object DisplayName -Unique
    foreach ($a in $apps) {
        Add-Line ('| {0} | {1} | {2} |' -f (Val $a.DisplayName), (Val $a.DisplayVersion), (Val $a.Publisher))
    }
}

# --------------------------------------------------------------- report output
Add-Line ''
Add-Line '---'
Add-Line ''
Add-Line ('_Generated by {0} {1} on host {2} at {3}._' -f $ScriptName, $Version, (Clean $env:COMPUTERNAME), (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))
Add-Line ''
Add-Line '<!-- End of report -->'

try {
    Set-Content -Path $OutputFile -Value $sb.ToString() -Encoding UTF8
    if (-not $Quiet) { Write-Host "Device audit report written to: $OutputFile" }
    exit 0
} catch {
    Write-Error "Cannot write $OutputFile : $($_.Exception.Message)"
    exit 1
}



