#!/usr/bin/env bash
# device-audit.sh -- collect endpoint/device information into a Markdown report.
# Works on Linux, macOS, and other Unix-like systems.
#
# Usage: ./device-audit.sh [-o FILE] [-s] [-q] [-h]

set -u

VERSION="1.0.0"
# Derive the program name without calling basename, which may be absent on
# minimal systems.
PROG="${0##*/}"
[ -n "$PROG" ] || PROG="device-audit.sh"

OUTFILE=""
INCLUDE_SOFTWARE=0
QUIET=0
NA="_n/a_"
CMD_TIMEOUT="${DEVICE_AUDIT_TIMEOUT:-3}"

usage() {
  cat <<EOF
$PROG $VERSION - collect device information into a Markdown report

Options:
  -o FILE   write report to FILE (default: device-audit-<host>-<timestamp>.md in $PWD)
  -s        include the list of installed software/packages (can be long)
  -q        quiet: only print the output path
  -h        show this help

Exit codes: 0 success, 1 usage error
EOF
}

while getopts "o:sqh" opt; do
  case "$opt" in
    o) OUTFILE="$OPTARG" ;;
    s) INCLUDE_SOFTWARE=1 ;;
    q) QUIET=1 ;;
    h) usage; exit 0 ;;
    *) usage >&2; exit 1 ;;
  esac
done

[ -n "$OUTFILE" ] || OUTFILE="device-audit-$(hostname 2>/dev/null || echo unknown)-$(date +%Y%m%d-%H%M%S).md"

have() { command -v "$1" >/dev/null 2>&1; }

# clean: collapse newlines, escape pipes, trim
clean() {
  printf '%s' "${1-}" | tr '\n\r\t' '   ' | sed 's/|/\\|/g; s/  */ /g; s/^ *//; s/ *$//'
}

val() { if [ -z "${1-}" ] || [ "${1-}" = "unknown" ] || [ "${1-}" = "not available" ]; then printf '%s' "$NA"; else printf '%s' "$1"; fi; }

kv() { printf '| %s | %s |\n' "$(clean "$1")" "$(val "$(clean "${2-}")")"; }
sec() { printf '\n## %s\n\n' "$1"; }

# Run a command, capture stdout, and swallow errors. Input is closed so that
# commands which would prompt for a password cannot block the report.
# The command's exit status is propagated so that "try a || try b" fallbacks work.
try() {
  local o rc=0
  o="$("$@" 2>/dev/null </dev/null)" || rc=$?
  [ -n "$o" ] || return "${rc:-1}"
  printf '%s' "$o"
  return 0
}

# Run a command with a timeout, storing the output in the global SLOW_OUT and
# setting SLOW_TIMED_OUT to 1 if the command had to be killed. Deliberately
# avoids a subshell so that the timeout flag survives (a TIMED_OUT set inside
# $(...) would be lost).
try_slow_var() {
  local tmp pid deadline
  SLOW_OUT=""
  SLOW_TIMED_OUT=0
  tmp="$(mktemp "${TMPDIR:-/tmp}/deviceaudit.XXXXXX" 2>/dev/null)" || return 1
  "$@" >"$tmp" 2>/dev/null </dev/null &
  pid=$!
  deadline=$(( SECONDS + CMD_TIMEOUT ))
  while kill -0 "$pid" 2>/dev/null; do
    if [ "$SECONDS" -ge "$deadline" ]; then
      kill -9 "$pid" 2>/dev/null
      SLOW_TIMED_OUT=1
      break
    fi
    sleep 0.2
  done
  wait "$pid" 2>/dev/null
  [ "$SLOW_TIMED_OUT" = "1" ] || SLOW_OUT="$(cat "$tmp")"
  rm -f "$tmp"
  return 0
}

# Same as try() but for commands known to block indefinitely on some systems
# (e.g. macOS `dsconfigstatus` and `softwareupdate`).
try_slow() {
  try_slow_var "$@" || return 1
  [ "$SLOW_TIMED_OUT" = "1" ] && return 1
  printf '%s' "$SLOW_OUT"
  return 0
}

UNAME_S="$(uname -s 2>/dev/null)"
case "$UNAME_S" in
  Darwin) IS_MAC=1; IS_LINUX=0 ;;
  Linux)  IS_MAC=0; IS_LINUX=1 ;;
  *)      IS_MAC=0; IS_LINUX=0 ;;
esac

# ---------------------------------------------------------------- report start
HOST="$(hostname 2>/dev/null || try uname -n)"

{
printf '# Device Audit Report\n\n'
printf -- '- **Host name:** %s\n' "$(clean "$HOST")"
printf -- '- **Report generated:** %s\n' "$(date '+%Y-%m-%d %H:%M:%S %Z')"
printf -- '- **Generated by:** %s %s\n' "$PROG" "$VERSION"
if [ "$(id -u 2>/dev/null)" = "0" ]; then
  printf -- '- **Privilege level:** root (elevated - some values may differ from user view)\n'
else
  printf -- '- **Privilege level:** standard user (some hardware values unavailable)\n'
fi
printf '\n'
} > "$OUTFILE" || { echo "$PROG: cannot write $OUTFILE" >&2; exit 1; }

{
# ------------------------------------------------------------------- overview
sec "Overview"
printf '| Field | Value |\n| --- | --- |\n'

OS_NAME="$(try sw_vers -productName)"
kv "Operating system" "${OS_NAME:-$(try uname -s)}"
kv "OS version" "$(try sw_vers -productVersion)"
kv "OS build" "$(try sw_vers -buildVersion)"
[ -n "$OS_NAME" ] || kv "OS distribution" "$(try . /etc/os-release 2>/dev/null; printf '%s' "${PRETTY_NAME-}")"
kv "Kernel" "$(try uname -r)"
kv "Kernel full" "$(try uname -v)"
kv "Architecture" "$(try uname -m)"
kv "Host name" "$HOST"
kv "Current user" "$(try id -un)"
kv "Uptime" "$(try uptime -p 2>/dev/null || try uptime)"
kv "Boot time" "$(try sysctl -n kern.boottime 2>/dev/null | sed 's/^.*} //' || try who -b 2>/dev/null | sed 's/^ *//')"
kv "Timezone" "$(try date +%Z) ($(try date +%z))"
kv "Locale" "$(try defaults read -g AppleLocale 2>/dev/null || try locale 2>/dev/null | head -1 | sed 's/^LANG=//; s/"//g')"

# ------------------------------------------------------------------- hardware
sec "Hardware"
printf '| Field | Value |\n| --- | --- |\n'
SYSINFO="$(try system_profiler SPHardwareDataType 2>/dev/null)"
kv "Model name" "$(printf '%s' "$SYSINFO" | awk -F': ' '/Model Name:/{print $2}')"
kv "Model identifier" "$(try sysctl -n hw.model 2>/dev/null)"
kv "Manufacturer" "$(try sysctl -n hw.manufacturer 2>/dev/null)"
CPU="$(printf '%s' "$SYSINFO" | awk -F': ' '/Processor Name:/{print $2}')"
[ -n "$CPU" ] || CPU="$(awk -F: '/model name/{gsub(/^ +/,"",$2); print $2; exit}' /proc/cpuinfo 2>/dev/null)"
[ -n "$CPU" ] || CPU="$(try sysctl -n machdep.cpu.brand_string 2>/dev/null)"
kv "CPU" "$CPU"
kv "CPU speed" "$(printf '%s' "$SYSINFO" | awk -F': ' '/Processor Speed:/{print $2}')"
kv "Cores (physical)" "$(printf '%s' "$SYSINFO" | awk -F': ' '/Total Number of Cores:/{print $2}' || try sysctl -n hw.physicalcpu 2>/dev/null || try nproc)"
kv "Cores (logical)" "$(try sysctl -n hw.logicalcpu 2>/dev/null || try nproc)"
kv "Memory" "$(printf '%s' "$SYSINFO" | awk -F': ' '/^ *Memory:/{print $2}' || awk '/MemTotal/{printf "%.2f GiB", $2/1048576}' /proc/meminfo 2>/dev/null)"
kv "Memory (bytes)" "$(try sysctl -n hw.memsize 2>/dev/null)"
SERIAL="$(printf '%s' "$SYSINFO" | awk -F': ' '/Serial Number/{print $2}')"
[ -n "$SERIAL" ] || SERIAL="$(try ioreg -rd1 -c IOPlatformExpertDevice 2>/dev/null | awk -F'"' '/IOPlatformSerialNumber/{print $4}')"
[ -n "$SERIAL" ] || SERIAL="$(cat /sys/class/dmi/id/product_serial 2>/dev/null)"
[ -n "$SERIAL" ] || SERIAL="$(cat /sys/class/dmi/id/chassis_serial 2>/dev/null)"
[ -n "$SERIAL" ] || SERIAL="$(cat /sys/class/dmi/id/board_serial 2>/dev/null)"
[ -n "$SERIAL" ] || SERIAL="$(try dmidecode -s system-serial-number 2>/dev/null)"
# Filter out common dummy BIOS strings
case "$SERIAL" in
  "None"|"Default string"|"System Serial Number"|"To be filled by O.E.M."|"Not Specified"|"0") SERIAL="" ;;
esac
kv "Serial number" "$SERIAL"
HW_UUID="$(try ioreg -rd1 -c IOPlatformExpertDevice 2>/dev/null | awk -F'= ' '/IOPlatformUUID/{print $2}' | tr -d '"')"
[ -n "$HW_UUID" ] || HW_UUID="$(cat /sys/class/dmi/id/product_uuid 2>/dev/null)"
[ -n "$HW_UUID" ] || HW_UUID="$(cat /etc/machine-id 2>/dev/null)"
kv "Hardware UUID" "$HW_UUID"
kv "Firmware version" "$(printf '%s' "$SYSINFO" | awk -F': ' '/Firmware Version:/{sub(/^[^:]*: /,""); print}')"
kv "Activation lock" "$(printf '%s' "$SYSINFO" | awk -F': ' '/Activation Lock Status:/{print $2}')"

# Linux-only hardware via sysfs / dmidecode
if [ "$IS_LINUX" = "1" ]; then
  kv "Vendor" "$(cat /sys/class/dmi/id/sys_vendor 2>/dev/null)"
  kv "Product" "$(cat /sys/class/dmi/id/product_name 2>/dev/null)"
  kv "Product version" "$(cat /sys/class/dmi/id/product_version 2>/dev/null)"
  kv "Board" "$(cat /sys/class/dmi/id/board_name 2>/dev/null)"
  kv "BIOS vendor" "$(cat /sys/class/dmi/id/bios_vendor 2>/dev/null)"
  kv "BIOS version" "$(cat /sys/class/dmi/id/bios_version 2>/dev/null)"
  kv "BIOS date" "$(cat /sys/class/dmi/id/bios_date 2>/dev/null)"
  kv "Chassis type" "$(cat /sys/class/dmi/id/chassis_type 2>/dev/null)"
  kv "Total RAM" "$(awk '/MemTotal/{printf "%.2f GiB", $2/1048576}' /proc/meminfo 2>/dev/null)"
  kv "Swap" "$(awk '/SwapTotal/{printf "%.2f GiB", $2/1048576}' /proc/meminfo 2>/dev/null)"
  kv "Virtualization" "$(try systemd-detect-virt 2>/dev/null || cat /sys/hypervisor/type 2>/dev/null)"
  kv "Secure boot" "$(try mokutil --sb-state 2>/dev/null)"
fi

# ------------------------------------------------------------------- storage
sec "Storage"
printf '| Device | Size | Type / Filesystem | Mounted on |\n| --- | --- | --- | --- |\n'

if [ "$IS_MAC" = "1" ]; then
  # Physical disks: the header line gives the device, and the partition rows
  # below it give the individual sizes.
  try diskutil list 2>/dev/null | awk '
    /^[[:space:]]*\/dev\/disk[0-9]+[[:space:]]/ {
      if (dev != "") printf "| %s | %s | %s | - |\n", dev, (size==""?"-":size), kind;
      line=$0; gsub(/^ +/,"",line);
      dev=line; sub(/ +.*$/,"",dev); size="";
      kind=""; if (match(line, /\(.*\)/)) kind=substr(line, RSTART+1, RLENGTH-2);
      next
    }
    dev != "" {
      if (size == "" && match($0, /[0-9]+(\.[0-9]+)?[ ]?[GMkT]B/)) size=substr($0, RSTART, RLENGTH);
      if ($0 ~ /^[[:space:]]*$/) { printf "| %s | %s | %s | - |\n", dev, (size==""?"-":size), kind; dev=""; size="" }
    }
    END { if (dev != "") printf "| %s | %s | %s | - |\n", dev, (size==""?"-":size), kind }
  '
  printf '\n'
  printf '| Volume | Size | File system | Mounted on |\n| --- | --- | --- | --- |\n'
  # system_profiler prints one block per volume: a 4-space indented "Name:"
  # header followed by 6-space indented "Key: value" lines. A block is flushed
  # when the next volume header (or "Physical Drive:") is seen.
  try system_profiler SPStorageDataType 2>/dev/null | awk '
    # Return the value part of an indented "      Key: value" line.
    function v(line,   s) { s=line; sub(/^ *[^:]*: */,"",s); return s }
    function flush() {
      if (vol != "") printf "| %s | %s | %s | %s |\n", vol, (cap==""?"-":cap), (fs==""?"-":fs), (mnt==""?"-":mnt);
      vol=""; cap=""; fs=""; mnt=""
    }
    /^ {4}[^ ].*:$/ {
      name=$0; gsub(/^ +/,"",name); sub(/:$/,"",name);
      if (name == "Physical Drive" || name == "Storage") { flush(); next }
      flush(); vol=name; next
    }
    vol != "" && /^ {6}Capacity:/    {cap=v($0); sub(/ \(.*/,"",cap); next}
    vol != "" && /^ {6}File System:/ {fs=v($0); next}
    vol != "" && /^ {6}Mount Point:/ {mnt=v($0); next}
    END{flush()}
  '
else
  if have lsblk; then
    try lsblk -o NAME,SIZE,TYPE,FSTYPE,MOUNTPOINT 2>/dev/null | awk 'NR>1 {
      printf "| /dev/%s | %s | %s %s | %s |\n", $1, $2, ($3==""?"-":$3), ($4==""?"-":$4), ($5==""?"-":$5)
    }'
  else
    # No lsblk (e.g. BusyBox or a minimal install): fall back to df.
    # The section header above is reused, so no extra header is printed here.
    try df -hP 2>/dev/null | awk 'NR>1 && NF>=6 && $1 !~ /^(map|devfs|devtmpfs|tmpfs|proc|autofs)/ {printf "| %s | %s | - | %s |\n", $1, $2, $NF}'
  fi
fi

printf '\n'
sec "Filesystem usage"
printf '| Filesystem | Size | Used | Avail | Use%% | Mounted on |\n| --- | --- | --- | --- | --- | --- |\n'
# GNU df accepts -hP; BSD/macOS df does not, so fall back to plain -P.
DF_CMD="df -P"
try df -hP >/dev/null 2>&1 </dev/null || DF_CMD="df -P"
if [ "$IS_MAC" = "1" ]; then DF_CMD="df -H"; fi
$DF_CMD 2>/dev/null | awk 'NR>1 && $1 !~ /^(map|devfs|devtmpfs|tmpfs|proc|autofs)/ {
  gsub(/%/,"",$5);
  printf "| %s | %s | %s | %s | %s%% | %s |\n", $1,$2,$3,$4,$5,$NF
}'

# ------------------------------------------------------------------- network
sec "Network"
printf '| Interface | MAC address | IPv4 address | State |\n| --- | --- | --- | --- |\n'
if [ "$IS_MAC" = "1" ]; then
  # Print each interface when the next one starts, so that all of its
  # addresses have been collected by then.
  try ifconfig 2>/dev/null | awk '
    function emit() {
      if (iface != "" && (mac != "" || ip != ""))
        printf "| %s | %s | %s | %s |\n", iface, (mac=="" ? "-" : mac), (ip=="" ? "-" : ip), st;
      iface=""; mac=""; ip=""; st="up"
    }
    /^[a-z0-9]+:/ {emit(); iface=substr($1, 1, length($1)-1); next}
    /^[[:space:]]*status:/ {st=$2; next}
    /^[[:space:]]*ether /{mac=$2; next}
    /^[[:space:]]*inet /{if (ip=="") ip=$2; next}
    END{emit()}
  '
else
  if have ip; then
    # `ip -o link` gives the MAC and state, `ip -o -4 addr` the IPv4 address.
    # Field positions vary between iproute2 versions, so scan for the keywords.
    MACS="$(try ip -o link 2>/dev/null | awk '
      { iface=$2; sub(/:$/,"",iface); mac="-"; st="unknown";
        for (i=1; i<=NF; i++) {
          if ($i == "link/ether" && $(i+1) != "") mac=$(i+1);
          if ($i == "state") st=$(i+1);
          if ($i == "NONE" || $i == "lo") mac="-";
        }
        print iface, mac, st }')"
    IPS="$(try ip -o -4 addr 2>/dev/null | awk '{print $2, $4}')"
    printf '%s\n' "$MACS" | awk -v ips="$IPS" '
      {
        split(ips, rows, "\n");
        iface=$1; mac=$2; st=$3; ip="-";
        if (mac == "00:00:00:00:00:00") mac="-";
        for (i=1; i<=length(rows); i++) {
          if (rows[i] == "" || index(rows[i], " ") == 0) continue;
          n=index(rows[i], " "); nm=substr(rows[i], 1, n-1);
          if (nm == iface) { ip=substr(rows[i], n+1); sub(/\/.*/,"",ip); break }
        }
        printf "| %s | %s | %s | %s |\n", iface, mac, ip, st;
      }'
  else
    try ifconfig 2>/dev/null | awk '/^[a-z0-9]+:/{i=$1} /ether /{print "| " i " | " $2 " | - | up |"}'
  fi
fi

printf '\n'
sec "Network configuration"
printf '| Field | Value |\n| --- | --- |\n'
kv "Hostname (FQDN)" "$(try hostname -f 2>/dev/null)"
kv "Primary IPv4" "$(try ipconfig getifaddr en0 2>/dev/null || try hostname -I 2>/dev/null | awk '{print $1}')"
kv "Default gateway" "$(try route -n get default 2>/dev/null | awk '/gateway:/{print $2}')"
kv "DNS servers" "$(try scutil --dns 2>/dev/null | awk '/nameserver\[0\]/{print $3}' | sort -u | tr '\n' ' ')"
kv "DNS servers (alt)" "$(try resolvectl dns 2>/dev/null | awk '{print $2}' | tr '\n' ' ')"
kv "Domain search" "$(try scutil --dns 2>/dev/null | awk '/search domain\[0\]/{print $4}')"
kv "Wi-Fi SSID" "$(try networksetup -getairportnetwork en0 2>/dev/null | sed 's/^Current Wi-Fi Network: //')"
kv "Proxy (HTTP)" "$(try scutil --proxy 2>/dev/null | awk '/HTTPEnable/{print $3}')"
kv "Proxy (HTTPS)" "$(try scutil --proxy 2>/dev/null | awk '/HTTPSEnable/{print $3}')"
kv "Directory service" "$(try_slow dsconfigstatus -show 2>/dev/null | tr '\n' ' ' || echo "$NA")"
} >> "$OUTFILE"
{


# ------------------------------------------------------------------ peripherals
sec "Displays"
printf '| Field | Value |\n| --- | --- |\n'
if [ "$IS_MAC" = "1" ]; then
  DISPINFO="$(try system_profiler SPDisplaysDataType 2>/dev/null)"
  kv "Display resolution" "$(printf '%s' "$DISPINFO" | awk -F': ' '/Resolution:/{r=$2} END{print r}')"
  kv "Display appearance" "$(printf '%s' "$DISPINFO" | awk -F': ' '/UI Looks like:/{print $2}')"
  kv "Display type" "$(printf '%s' "$DISPINFO" | awk -F': ' '/Display Type:/{print $2}')"
  kv "Graphics chipset(s)" "$(printf '%s' "$DISPINFO" | awk -F': ' '/Chipset Model:/{c=(c==""?$2:c ", " $2)} END{print c}')"
  kv "VRAM" "$(printf '%s' "$DISPINFO" | awk -F': ' '/VRAM .*:/{print $2}' | head -1)"
else
  kv "Displays" "$(try xrandr 2>/dev/null | grep ' connected' | awk '{print $1, $3}')"
  kv "Display count" "$(have xrandr && try xrandr 2>/dev/null | grep -c ' connected' || echo "$NA")"
fi

sec "Battery"
printf '| Field | Value |\n| --- | --- |\n'
if [ "$IS_MAC" = "1" ]; then
  BATT="$(try pmset -g batt 2>/dev/null)"
  kv "Power source" "$(printf '%s' "$BATT" | sed -n "s/.*from '\(.*\)'/\1/p")"
  kv "Charge level" "$(printf '%s' "$BATT" | grep -o '[0-9][0-9]*%' | head -1)"
  kv "Battery state" "$(printf '%s' "$BATT" | sed -n 's/.*%;\(.*\);.*/\1/p' | head -1)"
  kv "Battery details" "$(try system_profiler SPPowerDataType 2>/dev/null | awk -F': ' '/Cycle Count|Condition|MaxCapacity/{printf "%s=%s; ", $1, $2}')"
else
  [ -d /sys/class/power_supply ] || kv "Battery" "$NA"
  for d in /sys/class/power_supply/*; do
    [ -d "$d" ] || continue
    kv "Battery: $(basename "$d")" "$(cat "$d/type" 2>/dev/null)"
    kv "  Status" "$(cat "$d/status" 2>/dev/null)"
    kv "  Capacity %" "$(cat "$d/capacity" 2>/dev/null)"
    kv "  Energy now (mWh)" "$(cat "$d/energy_now" 2>/dev/null)"
    kv "  Model" "$(cat "$d/model_name" 2>/dev/null)"
    if [ -r "$d/energy_full" ] && [ -r "$d/energy_full_design" ]; then
      kv "  Health %" "$(awk -v a="$(cat "$d/energy_full")" -v b="$(cat "$d/energy_full_design")" 'BEGIN{ if (b>0) printf "%.1f", (a/b)*100 }')"
    fi
  done
fi

sec "Security"
printf '| Field | Value |\n| --- | --- |\n'
if [ "$IS_MAC" = "1" ]; then
  kv "FileVault" "$(try fdesetup status 2>/dev/null)"
  kv "Gatekeeper" "$(try spctl --status 2>/dev/null)"
  kv "SIP" "$(try csrutil status 2>/dev/null)"
  kv "Screen lock" "$(try sysadminctl -screenLock status 2>/dev/null)"
  kv "Password set" "$(try sysadminctl -secureTokenStatus 2>/dev/null)"
else
  kv "SELinux" "$(try getenforce 2>/dev/null || sestatus 2>/dev/null | head -1)"
  kv "AppArmor" "$(if have aa-status; then try aa-status --enabled >/dev/null 2>&1 && echo enabled || echo disabled; else echo "$NA"; fi)"
  kv "Firewall (ufw)" "$(try ufw status 2>/dev/null | head -1)"
  kv "Disk encryption" "$(if have lsblk; then try lsblk 2>/dev/null | grep -q crypt_luks && echo "LUKS detected" || echo "none detected"; else echo "$NA"; fi)"
  kv "Screen lock" "$(try gsettings get org.gnome.desktop.screensaver lock-enabled 2>/dev/null)"
fi
kv "Last login" "$(try last -n 1 2>/dev/null | head -1)"


# ------------------------------------------------------------------- software
sec "Software"
printf '| Field | Value |\n| --- | --- |\n'
if [ "$IS_MAC" = "1" ]; then
  kv "Xcode" "$(try xcodebuild -version 2>/dev/null | tr '\n' ' ')"
  kv "Python" "$(try python3 --version 2>/dev/null)"
  kv "Homebrew" "$(have brew && echo "installed" || echo "not installed")"
  # Count with a shell glob rather than ls, so this still works if ls is absent.
  APP_COUNT="$(set -- /Applications/*.app; [ -d "$1" ] && echo $# || echo 0)"
  kv "Applications in /Applications" "$APP_COUNT"
  # try_slow_var sets SLOW_OUT / SLOW_TIMED_OUT without a subshell, so the
  # timeout flag survives. A missing or killed command reports _n/a_, not a
  # false "0" which would suggest "no updates available".
  if have softwareupdate; then
    try_slow_var softwareupdate -l
    if [ "$SLOW_TIMED_OUT" = "1" ]; then
      kv "Pending updates" "$NA"
    else
      kv "Pending updates" "$(printf '%s' "$SLOW_OUT" | grep -c '^\*')"
    fi
  else
    kv "Pending updates" "$NA"
  fi
else
  kv "Distribution" "$( . /etc/os-release 2>/dev/null && printf '%s' "${PRETTY_NAME-}" )"
  # Only report a package count when the package manager actually exists,
  # otherwise a misleading "0" would be shown.
  kv "Packages (dpkg)" "$(have dpkg-query && dpkg-query -f '.\n' -W 2>/dev/null | wc -l | tr -d ' ' || echo "$NA")"
  kv "Packages (rpm)" "$(have rpm && rpm -qa 2>/dev/null | wc -l | tr -d ' ' || echo "$NA")"
  kv "Snap packages" "$(have snap && snap list 2>/dev/null | tail -n +2 | wc -l | tr -d ' ' || echo "$NA")"
  kv "Flatpak apps" "$(have flatpak && flatpak list 2>/dev/null | tail -n +2 | wc -l | tr -d ' ' || echo "$NA")"
  kv "Desktop environment" "$(printf '%s' "${XDG_CURRENT_DESKTOP-}")"
fi

if [ "$INCLUDE_SOFTWARE" = "1" ]; then
  printf '\n### Installed applications\n\n'
  printf '| Application | Version | Identifier |\n| --- | --- | --- |\n'
  if [ "$IS_MAC" = "1" ]; then
    for app in /Applications/*.app; do
      [ -d "$app" ] || continue
      av="$(try defaults read "$app/Contents/Info.plist" CFBundleShortVersionString 2>/dev/null | head -1)"
      au="$(try defaults read "$app/Contents/Info.plist" CFBundleIdentifier 2>/dev/null | head -1)"
      printf '| %s | %s | %s |\n' "$(clean "$(basename "$app" .app)")" "$(clean "${av:-unknown}")" "$(clean "${au:-unknown}")"
    done
  elif have dpkg-query; then
    dpkg-query -W -f='${binary:Package}|${Version}\n' 2>/dev/null |
      awk -F'|' 'NF>=2 {printf "| %s | %s | - |\n", $1, $2}' | head -400
  elif have rpm; then
    rpm -qa --qf '%{NAME}|%{VERSION}-%{RELEASE}\n' 2>/dev/null |
      awk -F'|' 'NF>=2 {printf "| %s | %s | - |\n", $1, $2}' | head -400
  else
    printf '| _package manager not detected_ | | |\n'
  fi
fi

printf '\n---\n\n'
printf '_Generated by %s %s on host %s at %s._\n' "$PROG" "$VERSION" "$(clean "$HOST")" "$(date '+%Y-%m-%d %H:%M:%S %Z')"
printf '\n<!-- End of report -->\n'
} >> "$OUTFILE"

[ "$QUIET" = "1" ] || printf 'Device audit report written to: %s\n' "$OUTFILE"
exit 0
